name: OLLVM Deflat

on:
  workflow_dispatch: # 允许手动触发

jobs:
  deflat:
    runs-on: ubuntu-latest
    
    # 【改动点】使用 angr 官方自带完善 Unicorn 环境的镜像！
    # 添加 options: --user root 防止 Actions Checkout 检出文件时发生权限报错
    container:
      image: angr/angr:latest
      options: --user root

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ==========================================
      # 此时我们已经身处配置好一切环境的 angr 官方容器内
      # 无需再使用 setup-python 和 pip install 浪费时间，直接运行！
      # ==========================================
      - name: Run Deobfuscation
        run: |
          # 1. 复制 SO 文件过去
          cp libfekit-9.3.20.so flat_control_flow/
          cd flat_control_flow
          
          # 2. 运行脚本！此时速度会飞快，因为 Unicorn 已经生效！
          python3 deflat.py -f libfekit-9.3.20.so --addr 0x967CE8
          
          # 3. 提取产物
          cp libfekit-9.3.20_recovered.so ../

      # ==========================================
      # 4. 上传产物
      # ==========================================
      - name: Upload Recovered Binary
        uses: actions/upload-artifact@v4
        with:
          name: deflat-recovered-so
          path: libfekit-9.3.20_recovered.so
